### ISSUE TITLE
dataset相关问题询问

### ISSUE THREAD

**Issue by zeqi2000** [maoxiaowei97/DRL4Route#1]
您好，可以解释一下dataset的数据格式吗。
另外原始数据集可以公开吗？

**Comment by maoxiaowei97** [comment]
您好，dataset的构建方式和数据格式在https://github.com/wenhaomin/LaDe，本工作用的是LaDe-P的数据，数据处理代码在route_prediction的data目录下，虽然本工作使用的数据和LaDe公开数据的时间范围不同，但数据格式是相同的，后续研究可以使用LaDe公开的数据。

**Comment by maoxiaowei97** [comment]
sloved
